services:
  front-app:
    container_name: front-app
    ports:
      - "3000:3000"
    tty: true
    environment:
      NODE_ENV: "production"
    healthcheck:
      test: ['CMD-SHELL', 'node -e "fetch(\"http://localhost:3000\").then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"']
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  back-server:
    build:
      context: .
      dockerfile: .devcontainer/backend/Dockerfile
    container_name: back-server
    working_dir: /backend
    env_file:
      - gcloud.env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/adc.json
      PYTHONPATH: /backend
    volumes:
      - "${ADC_JSON}:/var/secrets/adc.json:ro"
    ports:
      - "5000:5000"
    tty: true
    restart: unless-stopped