services:
  front-app:
    container_name: front-app
    ports:
      - "3000:3000"
    tty: true
    environment:
      NODE_ENV: "production"
    healthcheck:
      test: ['CMD-SHELL', 'wget -q -T 5 -O - http://localhost:3000/ > /dev/null 2>&1 || exit 1']
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  back-server:
    build:
      context: .
      dockerfile: .devcontainer/backend/Dockerfile
    container_name: back-server
    working_dir: /backend
    env_file:
      - gcloud.env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/adc.json
      PYTHONPATH: /backend
    volumes:
      - "${ADC_JSON}:/var/secrets/adc.json:ro"
    ports:
      - "5001:5000"
    tty: true
    restart: unless-stopped