services:
  front-app:
    build:
      context: .
      dockerfile: .devcontainer/frontend/Dockerfile.dev
    environment:
      NODE_ENV: "development"
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend/nextjs-project:/app:delegated
      - web-node-modules:/app/node_modules

  back-server:
    build:
      context: .
      dockerfile: .devcontainer/backend/Dockerfile
      args:
        POETRY_WITH: dev
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend/src:/backend/src

volumes:
  web-node-modules: