# 本番環境用の設定
services:
  front-app:
    build:
      context: .
      dockerfile: .devcontainer/frontend/Dockerfile.prod
    environment:
      NODE_ENV: "production"
  back-server:
    environment:
      - FLASK_ENV=production
    working_dir: /backend/src
    command: gunicorn -w 4 -b :5000 app:app

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-server
    depends_on:
      - front-app
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    restart: unless-stopped