import type { Metadata } from "next";
import { Yomogi } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import CssBaseline from "@mui/material/CssBaseline";

const yomogi = Yomogi({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-yomogi',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={yomogi.variable}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            {children} 
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
